config/routes.rb
Stackoverflow::Application.routes.draw do
  root :to => 'questions#index'

    resources :questions do 
      collection do
        get 'search'
	      get 'search_tag'
      end
      resources :answers, :only => [ :create, :update, :destroy ]
    end  

  resources :tags

  devise_for :users, :path_names=>{sign_in: 'authorization', sign_up: 'registration'}

end

app/models/answer.rb
class Answer < Post
  belongs_to :question
  default_scope { where(is_question: false) }
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	attr_accessible :title, :body, :user_id, :view, :is_question, :question_id

  #validates :is_question, :presence => true
	validates :title, :presence => true,
                    :length => { :minimum => 3 }

	# AVAILAVLE_TAB_METHODS = %w(my today week month)
	# def self.by_tab(method)
	# method = "all" unless AVAILAVLE_TAB_METHODS.include? method
	# 	Post.send method
	# end

  scope :my, lambda { |user| where(user_id: user.try(:id)) }
  scope :today, where(created_at: 1.day.ago..Time.now)
  scope :week, where(created_at: 1.week.ago..Time.now)
  scope :month, where(created_at: 1.month.ago..Time.now) 
  scope :fre, order("view desc").limit(10)

  # scope :search_q, lambda { |q| where(title: q) }
  scope :by_content, lambda { |q| where("title LIKE ? OR body LIKE ?", "%#{q}%", "%#{q}%") }

  def self.counter(id)
    p = Post.find(id)
    p.view + 1
  end

end

app/models/question.rb
class Question < Post
  has_many :answers
  has_many :question_tags
  has_many :tags, :through => :question_tags

  default_scope { where(is_question: true) }
  AVAILABLE_TABS = ["today", "week", "month", "fre"]

  def self.by_tab(tab, user)
    if tab == "my"
      Question.my(user) 
    elsif AVAILABLE_TABS.include?(tab)
      Question.send(tab)
    else
      Question.all
    end
  end 
end

app/models/question_tag.rb
class QuestionTag < ActiveRecord::Base
  attr_accessible :question, :tag
  belongs_to :question
  belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :posts
  has_many :question_tags
  has_many :questions, :through => :question_tags

  attr_accessible :name, :about, :related_tags, :questions_tagged

  scope :by_name, lambda { |q| where("name LIKE ?", "%#{q}%") }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  has_many :questions
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def index
    Answer.all
  end


  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.build(params[:answer])

    if @answer.save
      redirect_to question_path(@question)
    else
      #render :action => "show", :controller => "questions"
      render :template => "questions/show"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base	
  protect_from_forgery
end

app/controllers/questions_controller.rb
require "will_paginate/array"

class QuestionsController < ApplicationController

  # GET /questions
  def index
    @questions = Question.by_tab(params[:tab], current_user)#.by_user(current_user)
    @questions = @questions.paginate(:page => params[:page], :per_page => 4)
  end

  # GET /questions/1
  def show
    @question = Question.find(params[:id])
    @answer = Answer.new

    @question_tags = @question.question_tags

    # get answers number of qestion :id.
    @answ_num = @question.answers.all.count

    @question.update_attributes!(
       :view => Question.counter(params[:id])
    )
  end

  # GET /questions/new
  def new
    @question = Question.new
    @all_tags = Tag.all
  end

  # question /questions
  def create
    @question = current_user.questions.build(params[:question])  

    if @question.save

      Tag.find_all_by_id(params[:tags]).each do |tag|
        # QuestionTag.create(:question => @question, :tag => tag)
        @question.question_tags.create(:tag => tag)
      end
      redirect_to root_path

    else
      render :action => "new"
    end
  end


  # PUT /questions/1
  def edit    
    @question = Question.find(params[:id])

   @question_tags = @question.question_tags

  end

  def update
    @question = Question.find(params[:id])

    if @question.update_attributes(params[:question])

      Tag.find_all_by_id(params[:tags]).each do |tag|
         # QuestionTag.create(:question => @question, :tag => tag)
         @question.question_tags.create(:tag => tag)
      end
      redirect_to :action => :show, :id => @question.id
    else
      render 'edit'
    end
  end


  def search
    @search = Question.by_content(params[:q])
    respond_to do |format|
      format.html
         format.js { render :json => @search}
    end
  end

  def search_tag
    @search_tag = Tag.by_name(params[:q])

    respond_to do |format|
      format.js { render :json => @search_tag.to_json}
    end
  end

  # DELETE /questions/1
  def destroy
    @question = Question.find(params[:id])
    @question.destroy
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  # GET /posts
  def index
    @tags = Tag.all
  end

	# GET /posts/1
  def show
    @tag = Tag.find(params[:id])
  end

  # GET /posts/new
  def new
    @tag = Tag.new
  end

  # POST /posts
  def create
    @tag = Tag.new(params[:tag])
    if @tag.save		
      flash[:success] = "Tag created!"	
      redirect_to tags_path
    else
      render :action => "new"
    end
  end

  # DELETE /posts/1
  def destroy
    @tag = Tag.find(params[:id])
    if @tag.destroy
      redirect_to tags_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/answers/_form.html.haml
%h1
  Answer!
= form_for @answer do |f|
  = f.text_field :titile  
  = f.submit "Submit"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      Stackoverflow
    = favicon_link_tag 'favicon.ico'
    = javascript_include_tag "application"
    = stylesheet_link_tag "application", :media => "all"
    = csrf_meta_tags

  %body

    .div{ :class => "navbar navbar-inverse clearfix"}
      .div{ :class => "navbar-inner", :id => "custom-header"}
        .wrapper960
          - if user_signed_in? 
            %span{ :class => "brand"} 
              = current_user.email
            %span{ :class => "brand"}  
              = current_user.id
            %span  
              = link_to "Sign out", destroy_user_session_path, :method => :delete, :class => 'btn'
          - else 
            %span
              = link_to 'Sign in', new_user_session_path, :class => 'btn'
              = link_to 'Sign on', new_user_registration_path, :class => 'btn'  
      .wrapper960
        #header  
          #hlogo
            %h1
              Stackoverflow  
            = link_to '', root_path              
          #hmenus  
            .div{ :class => "nav mainnavs mainnavsanon"}
              %ul
                %li
                  = link_to 'Questions', questions_path
                %li
                  = link_to 'Tags', tags_path
                %li
                  = link_to 'Tour', '#'
                %li
                  = link_to 'Users', '#'
            .div{ :class => "nav askquestion"}    
              %ul
                %li  
                  = link_to 'Ask Question', new_question_path, :id => 'nav-askquestion'
    
    %section{ :class => "content-section"}   
      .wrapper960    
        = yield

app/views/posts/_form.html.haml
= form_for post, :url => url do |f|

  -#- if params[:action] == 'edit'
  -#  - @question_tags.each do |t|
  -#    = text_field_tag 'tags[]', t.tag_id, :type => 'hidden'

  %p
    = f.label :title
    %br
    = f.text_field :title 
  %p
    = f.label :body
    %br
    = f.text_area :body
  .search-tag
    .tag-editor
      %span.posted-tags
        - if params[:action] == 'edit'
          - @question_tags.each do |t|

            %span{:class => 'post-tag', :id => t.tag_id}
              = Tag.find(t.tag_id).name
              %span{:class => 'delete-tag'}

      = text_field_tag :q, nil, :autocomplete => 'off', :id => 'search_tags'
    .tag-suggestions
  %p
    = f.submit

app/views/posts/_post.html.haml
.div{ :id =>"question", :class => "clearfix" }
  #question-header
    %h1
      = post.title  
  .vote
    %a.vote-up-off
    %span.vote-count-question 
      0
    %a.vote-down-off    
  .question-text
    %p
      = post.body
  - if post.is_question?
    .question-taglist
      - @question_tags.each do |t|
        .post-tag{:title => Tag.find(t.tag_id).about}
          = Tag.find(t.tag_id).name

  .author-q-block
    .user-action-time
      %span{ :title => post.created_at.strftime("%B %d'%y at %H:%M")} 
        asked
        = post.created_at.strftime("%B %d'%y at %H:%M")

app/views/questions/_question.html.haml
.div{:id => "question_#{question.id}", :class => 'question-summary'}
  .statscontainer
    .statsarrow
    .votes
      .mini-counts
        345
      .div votes
    .answers
      .mini-counts      
        = question.answers.all.count
      .div answers
    .views
      .mini-counts
        = question.view
      .div views
  .summary
    %h3
      = link_to question.title, question      
    .excerpt
      = question.body
    .user-info
      .user-action-time
        Action time
      .user-details
        User id: 
        = question.user_id
      .destroy-btn
        = link_to "Destroy",  question, :confirm => "Sure?", :method => "delete", :remote => true, :class => 'delete_post'  
      .edit-btn
        = link_to 'Edit', edit_question_path(question)    

app/views/questions/_search_form.html.haml
= form_tag search_questions_path, :method => "get", :id => 'search_form', :remote => true do
  = label_tag(:q, "Search for question title:")
  = text_field_tag :q, nil, :autocomplete => 'off'
  = link_to 'X', '#', :class => 'clear_btn', :title => 'Clear'
  #search_res

app/views/questions/destroy.js.erb
$("#question_" + <%= @question.id.to_s %> ).fadeOut(function(){ $(this).remove(); });

app/views/questions/edit.html.erb
<ul class="breadcrumb">
  <li>
    <%= link_to 'Main', root_path %>
    <span class="divider">|</span>
  </li>
  <li>
    <%= link_to 'questions', questions_path %>
    <span class="divider">|</span>
  </li>
  <li>
    <%= link_to 'New', new_question_path %>
    <span class="divider">|</span>
  </li>
</ul>

<div class="search-question">
  <%= render 'questions/search_form' %>

<div class="new-question-form" id="new-question-form">

<legend>Edit question :</legend>
<%= render :partial => "posts/form", :locals => { :post => @question, :url => { :action => "update" }} %>

  <%= link_to 'Back', root_path, :class => "btn btn-primary" %>
 
</div>

app/views/questions/index.html.haml
%ul{ :class => "breadcrumb" }
  %li 
    %a 
      = link_to 'Main', root_path
      %span{ :class => "divider"} 
        |

.search-question
  = render 'questions/search_form'

.subheader
  %h1
    All Questions
  #tabs  
    = link_to 'all questions', questions_path(:tab => "all"), :class => "youarehere", :id => "tab-all"
    - if user_signed_in? 
      = link_to 'my questions', questions_path(:tab => "my"), :id => "tab-my"
    = link_to 'frequent', questions_path(:tab => "fre"), :id => "tab-fre"
    = link_to 'today', questions_path(:tab => "today"), :id => "tab-today"
    = link_to 'week', questions_path(:tab => "week"), :id => "tab-week"
    = link_to 'month', questions_path(:tab => "month"), :id => "tab-month"

#questions
  = render @questions
= will_paginate @questions    
  
= link_to 'Create new Tag', new_tag_path

app/views/questions/new.html.erb
<ul class="breadcrumb">
  <li>
    <%= link_to 'Main', root_path %>
    <span class="divider">|</span>
  </li>
  <li>
    <%= link_to 'questions', questions_path %>
    <span class="divider">|</span>
  </li>
  <li>
    <%= link_to 'New', new_question_path %>
    <span class="divider">|</span>
  </li>
</ul>

<div class="search-question">
  <%= render 'questions/search_form' %>

<div class="new-question-form" id="new-question-form">

<legend>Create new question :</legend>
<%= render :partial => "posts/form", :locals => { :post => @question, :url => questions_path} %>

<%= link_to 'Back', root_path, :class => "btn btn-primary" %>
 
</div>

app/views/questions/search.html.haml
%ul{ :class => "breadcrumb" }
  %li
    %a
      = link_to 'Main', root_path
      %span{ :class => "divider"}
        |
    %a
      = link_to 'Search', search_path
      %span{ :class => "divider"}
        |

.search-question
  %p
    Type to find questions:
  = render 'questions/search_form'

.subheader
  %h1
    Seach results..
- if @search.empty?
  .div{ :class => "div question-summary"}
    No Questions with Title like :
    %strong
      = params[:q]
- else
  = render @search

app/views/questions/show.html.haml
%ul{ :class => "breadcrumb" }
  %li 
    %a 
      = link_to 'Main', root_path
      %span{ :class => "divider"} 
        |
  %li 
    %a 
      = link_to 'questions', questions_path
      %span{ :class => "divider"} 
        |
  %li      
    %a 
      = @question.id 
      %span{ :class => "divider"} 

.search-question
  = render 'questions/search_form'
                
= render :partial => "posts/post", :locals => { :post => @question }

.ask_question
  %h1 
    = @question.answers.count
    Answers
    %hr
  // Viberem vse anseveri konkretnogo questiona.
  - @question.answers.each do |answer|
    = render :partial => "posts/post", :locals => { :post => answer }

  %h1 Your question
  = render :partial => "posts/form", :locals => { :post => @answer, :url => question_answers_path(@question)}

app/views/tags/_tag.html.haml
%td
  = link_to tag.name, root_path
  %hr
  %p
    = tag.about
  %hr  
  = link_to 'Destroy this tag', tag, method: :delete, data: { confirm: 'Are you sure?' } 

app/views/tags/_tagname.html.haml
%span.tags-data-list
  Autocompleate tags data-list:
  %span.tag-data 
    - @all_tags .each do |t|
      = t.name
      |

app/views/tags/index.html.haml
%ul{ :class => "breadcrumb" }
  %li 
    %a 
      = link_to 'Main', root_path
      %span{ :class => "divider"} 
        |
  %li 
    %a 
      = link_to 'Tags', tags_path
      %span{ :class => "divider"} 
        |

.subheader
  %h1
    All Tags

.tags_list  
  %table{ :class => "table table-striped table-bordered table-hover" }
    %tr
      = render @tags

= link_to 'Create new Tag', new_tag_path, :class => 'btn btn-primary'  

app/views/tags/new.html.haml
%ul{ :class => "breadcrumb" }
  %li 
    %a 
      = link_to 'Main', root_path
      %span{ :class => "divider"} 
        |
  %li 
    %a 
      = link_to 'Tags', tags_path
      %span{ :class => "divider"} 
        |
  %li      
    %a 
      New
      %span{ :class => "divider"}  

.subheader
  %h1
    Create new tag:

.div{ :class => "new-question-form", :id => "new-question-form" }
  = form_for :tag, :url => { :action => :create } do |f|
    %p
      = f.label :name
      %br
      = f.text_field :name
    %p
      = f.label :about
      %br
      = f.text_area :about  
    %p
      = f.submit

  = link_to 'Back to tag list', tags_path, :class => 'btn btn-primary'    
  

app/views/tags/show.html.haml
%ul{ :class => "breadcrumb" }
  %li 
    %a 
      = link_to 'Main', root_path
      %span{ :class => "divider"} 
        |
  %li 
    %a 
      = link_to 'Tags', posts_path
      %span{ :class => "divider"} 
        |
  %li      
    %a 
      = @tag.id 
      %span{ :class => "divider"}         

%h3 
  = @tag.name
%p
  = @tag.about

.author-q-block
  .user-action-time
    %span{ :title => @tag.created_at.strftime("%B %d'%y at %H:%M")} 
      asked
      = @tag.created_at.strftime("%B %d'%y at %H:%M")
    %hr

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>